### ISSUE TITLE
Rebuild after added files

### ISSUE THREAD

**Issue by theobouwman** [GoogleCloudPlatform/cloud-run-microservice-template-go#349]
I added a folder called `certs` with only `.pem`, `.cer`' etc files but the service cant find them.
Even when stoppen and starting the service this does not work. The service is able to find it when i run through CLI tho.

Thanks

**Comment by glasnt** [comment]
Hi @theobouwman.

When you want to make changes to a Cloud Run service, you need to rebuilt the application into a container, then deploy that new container. 

It sounds like you just tried to restart the service without a new container. Running the `gcloud builds submit` command from the README.md will create a new version of the container (as specified by the --image flag), then the `gcloud run deploy` command will then deploy the container (as specified by the --image flag). 

Hope that explanation helps!
